[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm install -g serve && serve dist -s -l $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
